name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3

      - name: ASDF Setup
        uses: asdf-vm/actions/setup@v2

      - name: Restore ASDF tools from cache
        id: asdf-tools-cache
        uses: actions/cache@v3
        with:
          key: asdf-tools-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            asdf-tools-
          path: |
            ${{ env.ASDF_DIR }}/plugins
            ${{ env.ASDF_DIR }}/installs

      - name: Install ASDF tools on cache-miss
        if: ${{ steps.asdf-tools-cache.outputs.cache-hit != 'true' }}
        uses: asdf-vm/actions/install@v2
        
      - name: Reshim installed ASDF tools
        shell: bash
        run: asdf reshim

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npm run build
